[package]
name = "terra-bindings"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of Terra Core"
repository = "https://github.com/CosmWasm/terra-contract/tree/master/packages/bindings"
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
